[project]
name = "med-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "dspy>=2.6.21",
    "fastapi[standard]>=0.115.12",
    "google-cloud-aiplatform>=1.90.0",
    "mcp>=1.9.1",
]
